Fix:Select Video->Capture Video　が動かない
lisb/android-mediashrink pull request #7
Opened 2024-11-11 04:59 UTC by takara727

サンプルアプリの `SelectVideo->CaptureVideo` が動かない。
カメラアプリがあっても `Activity#resolveActivity` が `null` を返してくるのが原因。 `resolveActivity(intent) != null` のときのみ `startActivityForResult` するのをやめ、 `startActivityForResult` して `ActivityNotFoundException` が発行された場合は Toast を表示する方式に変更した。

また、 deprecated だった `startActivityForResult` の利用をやめ `ActivityResultLauncher` を使う方式に変更した

2024-11-12 01:42 UTC, dYoshitakaKato approved these changes
ご対応ありがとうございます！
`RCODE_SELECT_FROM_GALLARY` が未使用になったので削除してよいように思います！

2024-11-12 01:42 UTC, dYoshitakaKato requested changes
間違えて Approve してしまいました。

2024-11-12 01:48 UTC, takara727 commented
@dYoshitakaKato 
> `RCODE_SELECT_FROM_GALLARY` が未使用になったので削除してよいように思います！

ご指摘ありがとうございます! 修正して force push しました
https://github.com/lisb/android-mediashrink/pull/7#pullrequestreview-2428421384

2024-11-12 11:48 UTC, y-gomi112358 approved these changes
問題ないように思います！

2024-11-19 02:27 UTC, dYoshitakaKato approved these changes
ご対応ありがとうございます。問題ないと思います！

2024-11-19 05:54 UTC, merged